modLoader="javafml"
# A version range to match for said mod loader - 45 is 1.19.4 or above
loaderVersion="[45,)"
license="Custom"
logoFile= "icon.png"
logoBlur=false
showAsResourcePack=false
clientSideOnly=true

[[mods]]
modId="make_bubbles_pop"
version="${file.jarVersion}-forge"
displayName="Make Bubbles Pop"
description='''
This client-side mod makes bubble particles pop and completely overhauls their behavior to make them rise realistically to the water surface.

It also adds bubble particles to opening chests, opening barrels and explosions underwater.
'''
authors="Tschipcraft"
displayURL="https://github.com/Tschipcraft/make_bubbles_pop"
issueTrackerURL="https://github.com/Tschipcraft/make_bubbles_pop/issues"
updateJSONURL="https://api.modrinth.com/updates/gPCdW0Wr/forge_updates.json"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.make_bubbles_pop]] #optional
    modId="forge"
    mandatory=true
    versionRange="[50,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.make_bubbles_pop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.make_bubbles_pop]]
    modId="midnightlib"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[modproperties.make_bubbles_pop]
    catalogueImageIcon="icon.png"
