modLoader="javafml"
# A version range to match for said mod loader - 40 is 1.18.2
loaderVersion="[40,41)"
license="Custom"
logoFile= "icon.png"
logoBlur=false
showAsResourcePack=false

[[mods]]
modId="make_bubbles_pop"
version="${file.jarVersion}-forge"
displayName="Make Bubbles Pop"
description='''This client-side mod makes bubble particles pop and completely overhauls their behavior to make them rise realistically to the water surface.

It also adds bubble particles to opening chests, opening barrels and explosions underwater.
'''
authors="Tschipcraft"
displayURL="https://github.com/Tschipcraft/make_bubbles_pop/tree/pre-1.19.4"
issueTrackerURL="https://github.com/Tschipcraft/make_bubbles_pop/issues"
updateJSONURL="https://api.modrinth.com/updates/gPCdW0Wr/forge_updates.json"
#displayTest="IGNORE_ALL_VERSION"

[[dependencies.make_bubbles_pop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"

[modproperties.make_bubbles_pop]
    catalogueImageIcon="icon.png"
